services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '1001:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
